name: worldtimeapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'  # Update this to match your Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2  # Update to the latest version that supports null safety
  intl: ^0.19.0  # Update to the latest version that supports null safety
  flutter_spinkit: ^5.2.1  # Ensure this version supports null safety
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Ensure this version supports null safety

flutter:
  uses-material-design: true
  assets:
    - assets/
